# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f6264cf0635f66761ccc688c24d8c2824e857c8ffc8e399ed9af08fbfd5d54e1b547b2ddeb26ff8e493715b1aa71d0723ecf8b24692ddac3326306553b10e84b

test:
  secret_key_base: e5a663f2e3d11fd9fefbbe3d0c4e45e14edf391637e3f096723f2a5db197389587426822a23784721141865db89e2a6887ec1923e2a593d62b19a7f9c93352b7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
